# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SVNewsletter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SVNewsletter
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'

  target 'SVNewsletterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
